version: '3.8'

services:
  pg:
    image: postgres
    environment:
      POSTGRES_DB: pub
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d pub"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      bash -c "cd /app/src &&
               alembic upgrade head &&
               uvicorn main:main_app --host 0.0.0.0 --port 8000 --reload"
    depends_on:
      pg:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@pg:5432/pub
    volumes:
      - ./src:/app/src
    ports:
      - "8000:8000"

  # Если нужно добавить другие сервисы (например, фронтенд), можно добавить их сюда.
